### ISSUE TITLE
Document the behavior of move constructor for slist

### ISSUE THREAD

**Issue by ldionne** [boostorg/intrusive#25]
The documentation for `boost::intrusive::slist`'s move constructor and move assignment operator currently states `to-do`, which leaves me wondering what their behavior is:

![screen shot 2017-10-02 at 21 29 22](https://user-images.githubusercontent.com/700834/31110024-e26475cc-a7b8-11e7-9240-cba4204e2b7d.png)

**Comment by igaztanaga** [comment]
Thanks for the report!
