### ISSUE TITLE
Stateful node_traits for rbtree

### ISSUE THREAD

**Issue by iassenev** [boostorg/intrusive#32]
Hi!

Are there any plans on making a possibility to have a stateful node_traits class?

Then one can store not pointers, but indices in his custom node_traits and when there is a need for a conversion, node_traits state can be used. It is ok if there is a need to copy node_traits instance from time to time.

Kind regards,
Dmitriy

**Comment by igaztanaga** [comment]
Sorry for missing this issue. Response: there are no plans to support stateful node_traits because it would highly complicate the implementation.

**Comment by iassenev** [comment]
Is there any way to store in a tree indices instead of pointers? Now I just use a separate custom node_traits *class* for a range of pointers, but I need to pass somehow a beginning of a range of pointers to an instance of a node_traits class.

Is there something I missed and this can be done right now without stateful node_traits?
