### ISSUE TITLE
UB due to union based type punning

### ISSUE THREAD

**Issue by Flamefire** [boostorg/intrusive#46]
https://github.com/boostorg/intrusive/blob/3b5001f22f342e62a6f732b0bc58817a608a752f/include/boost/intrusive/detail/math.hpp#L215 uses an union to convert a float to an int. This has 2 problems each causing UB:

1. a float may not be a IEEE754 float (I think this can be checked via defines)
2. Accessing an inactive union member is UB (this can be fixed by a memcpy which is optimized away by the compiler)

**Comment by igaztanaga** [comment]
1. The implementation does not support anything that is not IEEE754, which is extremly rare there days, so this won't be fixed.

2. As you suggest, a memcpy is the correct fix.
