### ISSUE TITLE
constexpr

### ISSUE THREAD

**Issue by igoloe** [boostorg/intrusive#47]
I am using intrusive now for a very long time. From a memory managment perspective it maybe possible to make intrusie constexpr? Ofc reinterpret_cast or void* may be a problem.

**Comment by igaztanaga** [comment]
It seems to me that constexpr-ing would be quite difficult. Even with base hooks, there are too many casts to support it.

**Comment by burnpanck** [comment]
How about a constexpr default constructor? This would enable using intrusive containers in `constinit` globals, which we use extensively in our embedded bare-metal firmware. Knowing no "user code" runs early helps peace of mind that there will be no failures before the OS itself boots.
