### ISSUE TITLE
*set.rbegin() looks like O(log(N))

### ISSUE THREAD

**Issue by XeCycle** [boostorg/intrusive#54]
[This commit](https://github.com/boostorg/intrusive/commit/6a9fa390aed83a8e8c1b1ef92f3b2f6cb5e93bce#diff-1d08730f04a8a30388466fc45aec4fbd7037f47c3c050cee82aab373d300ea6cL72) from 2015 flipped its implementation, but the commit message does not seem relevant.  So we can indeed support O(1) `back()`-like operation, but there's no dedicated `back()` and this one became O(log(N)).  I'm not sure whether that's an intentional change to conform to other changes, or just a mistake?

(The [diagram comment](https://github.com/boostorg/intrusive/blob/develop/include/boost/intrusive/bstree_algorithms.hpp#L109) says the header's right child always points to rightmost node.)

**Comment by igaztanaga** [comment]
Thanks for the report!
