### ISSUE TITLE
Add noexcept support to the library

### ISSUE THREAD

**Issue by impugachev** [boostorg/intrusive#59]
Why doesn't the library use `noexcept` anywhere? I work in an environment with no exceptions, so intrusive containers are exactly what I need, but when using Boost.Intrusive, there are some problems due to the complete lack of `noexcept`.

**Comment by igaztanaga** [comment]
The reason is that Intrusive was written long before noexcept was available. Any hint on which operations are most needed to be noexcept?

**Comment by impugachev** [comment]
First of all, hook constructors. Because of them, when inheriting, you have to explicitly write an empty noexcept constructor.

**Comment by igaztanaga** [comment]
Thanks for the feedback. I plan to implement firs noexcept support for the next release.

**Comment by igaztanaga** [comment]
Thanks for the report. Let me know if the support is enough or I missed something important.

**Comment by impugachev** [comment]
Many thanks! It looks like everything I need is here. I'll write if I find anything else while using it.
