### ISSUE TITLE
Support B+ tree

### ISSUE THREAD

**Issue by adolfogc** [boostorg/intrusive#72]
The implementation from the tlx library, provided under the Boost license, could be adapted to align with Boost.Intrusive.

See: https://github.com/tlx/tlx/blob/1b2059e19f3605c854f2a7450fa102e3e40dc10e/tlx/container/btree.hpp#L104

**Comment by igaztanaga** [comment]
Thanks for the suggestion, but it should be targeted to another Boost library, as a B+tree can't be buit as an intrusive container (in B+ trees keys are stored in internal nodes and values in leaves), so I don't think Boost.Intrusive is the correct place for such a container.
