### ISSUE TITLE
<functional> might not be included soon enough when building treap_multiset_test.cpp

### ISSUE THREAD

**Issue by dkrejsa** [boostorg/intrusive#80]
Working with a set of proprietary C++ headers derived from Dinkum, building the treap_multiset_test.cpp test fails due to the definition of `std::greater<T>` not being visible yet at the point in generic_multiset_test.hpp where it is used.

In this environment the <functional> header does not appear to be included at that point yet, although it is included later.
Adding

    #include <functional>

immediately after the include of `<typeinfo>` in generic_multiset_test.hpp, appears to fix the problem.

**Comment by igaztanaga** [comment]
Many thanks for the report!
