### ISSUE TITLE
[docs] Index is missing

### ISSUE THREAD

**Issue by Lastique** [boostorg/intrusive#83]
At least in Boost 1.84.0, the Indexes section in the docs seem to be not compiled correctly:

https://www.boost.org/doc/libs/1_84_0/doc/html/intrusive/index.html

**Comment by igaztanaga** [comment]
It seems that the index was lost between between Boost 1.58 and Boost 1.59. After investigating the reason for longer than I'd expect, it seems that upgrading the quickbook languange version from [quickbook 1.5] to [quickbook 1.6] broke the index inclusion.

I'll follow Boost.Math's index generation commands that are compatible with Quickbook 1.7. Many thanks for the issue.
