### ISSUE TITLE
Invalid UTF-8 character in comment

### ISSUE THREAD

**Issue by francoisk** [boostorg/intrusive#86]
MSVC 17 and gcc 13 and 14 report the following:

```
include/boost/intrusive/detail/hash.hpp:5:27: warning: invalid UTF-8 character <f1> [-Winvalid-utf8]
```

Code point `00F1` has to be encoded in two bytes but here it's in a single byte.

Note that I used `-std=c++26 -finput-charset=UTF-8` and `/std:c++20 /utf-8`.

**Comment by igaztanaga** [comment]
Thanks for the report!
